# Support functions for the Shiny design app (inst/app/app.R). These are UI,
# interpolation and input-normalisation helpers ONLY. Every statistical quantity
# still comes from the package's cgr_* functions - the app never carries its own
# copy of the estimand.

# Accessor for the precomputed operating-characteristics lookup table shipped in
# inst/extdata (generated by data-raw/build_lookup.R). One row per
# (n, p_cg, true_effect) x (DTE, AEB) scenario. cgr_operating(n_trials = 500)
# takes ~9 s, so the app reads this instead of calling it on a slider.
cgrc_lookup <- function() {
  f <- system.file("extdata", "cgrc_lookup.rds", package = "cgrc.bayes")
  if (!nzchar(f) || !file.exists(f)) {
    stop("lookup table not found; run data-raw/build_lookup.R then reinstall.",
         call. = FALSE)
  }
  readRDS(f)
}

# Launch the Shiny design app ("Is CGR adjustment safe for my trial?").
cgrc_app <- function(...) {
  if (!requireNamespace("shiny", quietly = TRUE)) {
    stop("the app needs the 'shiny' package: install.packages('shiny')",
         call. = FALSE)
  }
  app_dir <- system.file("app", package = "cgrc.bayes")
  if (!nzchar(app_dir)) stop("app directory not found in the install", call. = FALSE)
  shiny::runApp(app_dir, ...)
}

# Bilinear interpolation of a single column over two grid axes.
.cgrc_bilin <- function(df, xcol, ycol, vcol, x, y) {
  xs <- sort(unique(df[[xcol]])); ys <- sort(unique(df[[ycol]]))
  x <- min(max(x, min(xs)), max(xs)); y <- min(max(y, min(ys)), max(ys))
  x0 <- max(xs[xs <= x]); x1 <- min(xs[xs >= x])
  y0 <- max(ys[ys <= y]); y1 <- min(ys[ys >= y])
  g  <- function(xx, yy) df[[vcol]][df[[xcol]] == xx & df[[ycol]] == yy][1]
  tx <- if (x1 == x0) 0 else (x - x0) / (x1 - x0)
  ty <- if (y1 == y0) 0 else (y - y0) / (y1 - y0)
  (1 - tx) * (1 - ty) * g(x0, y0) + tx * (1 - ty) * g(x1, y0) +
    (1 - tx) * ty * g(x0, y1) + tx * ty * g(x1, y1)
}

# Operating characteristics for one (DTE, AEB) scenario at arbitrary (n, p_cg),
# a grid true_effect and a grid mu_aeb (expectancy magnitude), read from the
# lookup. Bilinear in (n, p_cg); true_effect and mu_aeb are snapped to their
# nearest grid values. `mu_aeb` only matters for AEB-on rows (with AEB off there
# is no expectancy term). Returns a one-row data.frame of interpolated metrics
# plus an `interpolated` flag. Works whether or not the lookup has a mu_aeb
# column (older 7.7-only tables are treated as a single level).
cgrc_op_at <- function(lut, n, p_cg, true_effect, dte, aeb, mu_aeb = 7.7) {
  sub <- lut[lut$DTE == dte & lut$AEB == aeb, ]
  ma  <- NA_real_
  if ("mu_aeb" %in% names(sub)) {
    mas <- sort(unique(sub$mu_aeb)); ma <- mas[which.min(abs(mas - mu_aeb))]
    sub <- sub[sub$mu_aeb == ma, ]
  }
  effs <- sort(unique(sub$true_effect))
  eff  <- effs[which.min(abs(effs - true_effect))]
  sub  <- sub[sub$true_effect == eff, ]
  if (!nrow(sub)) stop("no lookup rows for that scenario", call. = FALSE)
  # a matched-to-two-sided-p<0.05 comparator is available in newer lookups
  metrics <- c("unadj_bias", "adj_bias", "adj_rmse", "coverage95",
               "p_fav_gt_95", "freq_sig", "empty_stratum_rate")
  if ("p_fav_gt_975" %in% names(sub)) metrics <- c(metrics, "p_fav_gt_975")
  vals <- vapply(metrics, function(m) .cgrc_bilin(sub, "n", "p_cg", m, n, p_cg),
                 numeric(1))
  on_grid <- n %in% sub$n && p_cg %in% sub$p_cg
  # clamped: the requested n or p_cg is OUTSIDE this level's grid, so an edge
  # value is being reported under the requested label (e.g. n=60 is not
  # simulated at mu_aeb != 7.7, so it reads the n=80 row). Flag it, do not hide.
  clamped <- n < min(sub$n) || n > max(sub$n) ||
             p_cg < min(sub$p_cg) || p_cg > max(sub$p_cg)
  cbind(data.frame(n = n, p_cg = p_cg, true_effect = eff, mu_aeb = ma,
                   DTE = dte, AEB = aeb,
                   interpolated = !on_grid, clamped = clamped),
        as.data.frame(as.list(vals)))
}

# Power of the ADJUSTED analysis to detect true_effect, over n, at fixed p_cg.
# This is the DTE-on / AEB-off row - the honest, expectancy-free power (the
# AEB-on rows mix drug and expectancy, so their p_fav is not clean power).
# With AEB off the expectancy magnitude is irrelevant, so mu_aeb does not enter.
cgrc_power_curve <- function(lut, p_cg, true_effect) {
  ns <- sort(unique(lut$n))
  data.frame(n = ns,
             power = vapply(ns, function(nn)
               cgrc_op_at(lut, nn, p_cg, true_effect, 1, 0)$p_fav_gt_95,
               numeric(1)))
}

# Accessor for the precomputed UNKNOWN-preserving operating-characteristics
# lookup (inst/extdata/cgrc_unknown_lookup.rds, built by
# data-raw/build_unknown_lookup.R). Returns NULL if it has not been built, so the
# app can fall back gracefully rather than error.
cgrc_unknown_lookup <- function() {
  f <- system.file("extdata", "cgrc_unknown_lookup.rds", package = "cgrc.bayes")
  if (!nzchar(f) || !file.exists(f)) return(NULL)
  readRDS(f)
}

# Operating characteristics of the UNKNOWN estimator for one (DTE, AEB) scenario
# at arbitrary (n, p_cg), read from the UNKNOWN lookup. Mirrors cgrc_op_at():
# bilinear in (n, p_cg); true_effect and u are snapped to their nearest grid
# levels. Returns a one-row data.frame plus interpolated/clamped flags.
cgrc_unknown_op_at <- function(lut, n, p_cg, true_effect, u, dte, aeb) {
  sub <- lut[lut$DTE == dte & lut$AEB == aeb, ]
  us  <- sort(unique(sub$u)); uu <- us[which.min(abs(us - u))]
  sub <- sub[sub$u == uu, ]
  effs <- sort(unique(sub$true_effect)); eff <- effs[which.min(abs(effs - true_effect))]
  sub  <- sub[sub$true_effect == eff, ]
  if (!nrow(sub)) stop("no UNKNOWN-lookup rows for that scenario", call. = FALSE)
  metrics <- c("unadj_bias", "adj_bias", "adj_rmse", "coverage95",
               "p_fav_gt_95", "p_fav_gt_975", "freq_sig", "empty_stratum_rate")
  metrics <- metrics[metrics %in% names(sub)]
  vals <- vapply(metrics, function(m) .cgrc_bilin(sub, "n", "p_cg", m, n, p_cg),
                 numeric(1))
  on_grid <- n %in% sub$n && p_cg %in% sub$p_cg
  clamped <- n < min(sub$n) || n > max(sub$n) ||
             p_cg < min(sub$p_cg) || p_cg > max(sub$p_cg)
  cbind(data.frame(n = n, p_cg = p_cg, true_effect = eff, u = uu,
                   DTE = dte, AEB = aeb,
                   interpolated = !on_grid, clamped = clamped),
        as.data.frame(as.list(vals)))
}

# Power of the ADJUSTED UNKNOWN estimator over n, at fixed p_cg, u and effect
# (the DTE-on / AEB-off row - clean, expectancy-free power).
cgrc_unknown_power_curve <- function(lut, p_cg, true_effect, u) {
  ns <- sort(unique(lut$n))
  data.frame(n = ns,
             power = vapply(ns, function(nn)
               cgrc_unknown_op_at(lut, nn, p_cg, true_effect, u, 1, 0)$p_fav_gt_95,
               numeric(1)))
}

# Plain-language verdict for an UNKNOWN-preserving design, computed from the
# UNKNOWN lookup (never hand-written). States the same trade-off cgrc_verdict()
# does, but names the directional CGR and the held UNKNOWN rate, and does not
# pronounce a design "safe".
cgrc_unknown_verdict <- function(lut, n, p_cg, true_effect, u) {
  minstr <- cgr_unknown_min_stratum(n, p_cg, u)
  fp  <- cgrc_unknown_op_at(lut, n, p_cg, true_effect, u, 0, 1)   # pure expectancy
  feas <- if (minstr < 15) sprintf(
    paste0(" (The smallest of the six strata averages ~%.0f participants here, so ",
           "the estimand can be undefined for some trials - see feasibility.)"),
    minstr) else ""
  if (true_effect == 0) {
    sprintf(paste0("UNKNOWN-preserving design at n=%d, directional CGR %.0f%%, ",
      "UNKNOWN rate %.0f%%, no true effect: when the apparent signal is pure ",
      "expectancy, the naive analysis reaches p<0.05 in %.0f%% of simulated ",
      "trials, while the UNKNOWN-adjusted analysis reaches posterior P>0.95 in ",
      "%.0f%%.%s"),
      n, 100 * p_cg, 100 * u, 100 * fp$freq_sig, 100 * fp$p_fav_gt_95, feas)
  } else {
    pw <- cgrc_unknown_op_at(lut, n, p_cg, true_effect, u, 1, 0)   # clean power
    sprintf(paste0("UNKNOWN-preserving design at n=%d, directional CGR %.0f%%, ",
      "UNKNOWN rate %.0f%%: for a real %.1f-point effect the UNKNOWN-adjusted ",
      "analysis reaches posterior P>0.95 in %.0f%% of simulated trials. When the ",
      "apparent effect is instead pure expectancy, the naive analysis reaches ",
      "p<0.05 in %.0f%% and the adjusted analysis in %.0f%%.%s"),
      n, 100 * p_cg, 100 * u, true_effect, 100 * pw$p_fav_gt_95,
      100 * fp$freq_sig, 100 * fp$p_fav_gt_95, feas)
  }
}

# Normalise an arm / guess coding to "AC"/"PL", erroring (naming the offending
# level) rather than guessing. Accepts AC/PL, MD/PL, active/placebo,
# drug/placebo, microdose/placebo, 1/0, TRUE/FALSE, yes/no.
cgrc_normalise_arm <- function(x, what = "value") {
  s <- toupper(trimws(as.character(x)))
  active  <- c("AC", "MD", "ACTIVE", "DRUG", "MICRODOSE", "TREATMENT",
               "TRUE", "T", "1", "YES", "Y")
  placebo <- c("PL", "PLACEBO", "CONTROL", "SHAM", "FALSE", "F", "0", "NO", "N")
  out <- ifelse(s %in% active, "AC", ifelse(s %in% placebo, "PL", NA_character_))
  bad <- unique(as.character(x)[is.na(out)])
  if (length(bad)) {
    stop(sprintf(paste0("could not map %s level(s) %s to active/placebo; ",
                        "recode to AC/PL (active/placebo)."),
                 what, paste(shQuote(bad), collapse = ", ")), call. = FALSE)
  }
  out
}

# Normalise a GUESS coding to "AC"/"PL"/"UNKNOWN". Unlike cgrc_normalise_arm(),
# this optionally recognises an explicit UNKNOWN / "I do not know" response and
# keeps missing data (NA or blank) as missing - an observed UNKNOWN response and
# absent data are different things and must not be conflated. Unrecognised values
# error, naming the offending labels, rather than being guessed. When
# allow_unknown = FALSE an UNKNOWN synonym is treated as unrecognised (rejected
# explicitly), so the caller cannot silently admit UNKNOWN into a binary analysis.
cgrc_normalise_guess <- function(x, allow_unknown = FALSE, unknown_labels = NULL,
                                 what = "treatment guessed") {
  raw <- as.character(x)
  s <- toupper(trimws(raw))
  # normalise apostrophe variants to a plain ' with fixed byte replacement so this
  # works in a C locale too, where a multibyte regex character class fails. \u
  # escapes keep the source pure-ASCII; useBytes avoids any locale translation.
  for (ap in c("\u2019", "\u02bc", "\u2018", "`"))
    s <- gsub(ap, "'", s, fixed = TRUE, useBytes = TRUE)
  s <- gsub("[[:space:]]+", " ", s)             # collapse internal whitespace
  active  <- c("AC", "MD", "ACTIVE", "DRUG", "MICRODOSE", "TREATMENT",
               "TRUE", "T", "1", "YES", "Y")
  placebo <- c("PL", "PLACEBO", "CONTROL", "SHAM", "FALSE", "F", "0", "NO", "N")
  unknown <- c("UNKNOWN", "UNSURE", "UNCERTAIN", "NOT SURE", "DO NOT KNOW",
               "DON'T KNOW", "DONT KNOW", "DID NOT KNOW", "DIDN'T KNOW",
               "DIDNT KNOW", "I DO NOT KNOW", "I DON'T KNOW", "I DONT KNOW",
               "DK", "IDK", "NO IDEA", "CAN'T TELL", "CANT TELL",
               toupper(trimws(as.character(unknown_labels))))
  missing <- is.na(raw) | s == ""               # NA / blank stay missing, never UNKNOWN
  out <- rep(NA_character_, length(s))
  out[s %in% active]  <- "AC"
  out[s %in% placebo] <- "PL"
  if (allow_unknown) out[s %in% unknown] <- "UNKNOWN"
  out[missing] <- NA_character_
  bad <- unique(raw[!missing & is.na(out)])      # present, but mapped to nothing
  if (length(bad)) {
    hint <- if (allow_unknown) "AC/PL or an UNKNOWN response" else "AC/PL (active/placebo)"
    stop(sprintf("could not map %s level(s) %s to %s; recode them.",
                 what, paste(shQuote(bad), collapse = ", "), hint), call. = FALSE)
  }
  out
}

# Input audit for an uploaded trial. Classifies every row instead of silently
# dropping it with complete.cases(): a row can be missing its condition, missing
# its guess, an observed UNKNOWN response (NOT an exclusion - kept when preserving
# UNKNOWN), missing its outcome, or a non-numeric outcome. A genuinely
# unmappable code (e.g. "banana") still errors via the normalisers - that is a
# data error, not a missing value. Returns the clean analysis frame, an exclusion
# log, a count summary, and whether any UNKNOWN responses were seen. Blank/NA are
# missing; an observed UNKNOWN is not.
cgrc_input_audit <- function(condition, guess, value, unknown_level = "UNKNOWN") {
  n  <- length(condition)
  cr <- trimws(as.character(condition)); gr <- trimws(as.character(guess))
  vr <- as.character(value)
  miss_c <- is.na(condition) | cr == ""
  miss_g <- is.na(guess)     | gr == ""
  miss_v <- is.na(value)     | trimws(vr) == ""
  vnum   <- suppressWarnings(as.numeric(vr))
  nonnum <- !miss_v & is.na(vnum)

  cond <- rep(NA_character_, n); g <- rep(NA_character_, n)
  if (any(!miss_c))
    cond[!miss_c] <- cgrc_normalise_arm(condition[!miss_c], "treatment received")
  if (any(!miss_g))
    g[!miss_g] <- cgrc_normalise_guess(guess[!miss_g], allow_unknown = TRUE,
                                       unknown_labels = unknown_level)
  is_unknown <- !miss_g & !is.na(g) & g == "UNKNOWN"

  # exclusion reason, by precedence (a missing condition wins over a bad outcome)
  reason <- rep("ok", n)
  reason[nonnum] <- "non-numeric outcome"
  reason[miss_v] <- "missing outcome"
  reason[miss_g] <- "missing guess"
  reason[miss_c] <- "missing condition"
  excluded <- reason != "ok"

  summary <- c(n_input = n,
               missing_condition  = sum(miss_c),
               missing_guess      = sum(miss_g),
               observed_unknown   = sum(is_unknown),
               missing_outcome    = sum(miss_v),
               nonnumeric_outcome = sum(nonnum),
               excluded           = sum(excluded),
               n_analysis         = sum(!excluded))
  list(
    clean = data.frame(condition = cond[!excluded], guess = g[!excluded],
                       value = vnum[!excluded], stringsAsFactors = FALSE),
    log = data.frame(row = which(excluded), reason = reason[excluded],
                     stringsAsFactors = FALSE),
    summary = summary,
    has_unknown = sum(is_unknown) > 0)
}

# Build a self-contained Markdown analysis report from the app's assembled
# analysis object `f` (see inst/app/app.R). Contains the input audit, exclusions,
# stratum counts, observed CGR and UNKNOWN rate, raw and adjusted estimates, the
# identity check, posterior probabilities, ROPE results, warnings, the package
# version, the random seed, and an exact method description. Returns a character
# vector of lines. Kept in the package (not app.R) so it is testable and so the
# app carries no statistics of its own.
cgrc_build_report <- function(f) {
  ver <- tryCatch(as.character(utils::packageVersion("cgrc.bayes")), error = function(e) "NA")
  s <- f$audit$summary
  L <- c()
  add <- function(...) L <<- c(L, sprintf(...))
  add("# CGRC analysis report")
  add("")
  add("- Generated: %s", format(Sys.time(), "%Y-%m-%d %H:%M:%S"))
  add("- Package: cgrc.bayes %s", ver)
  add("- Random seed: %s", if (is.null(f$seed)) "not set" else as.character(f$seed))
  meth <- if (f$mode == "unknown")
    paste("UNKNOWN-preserving CGRC extension (six strata; observed UNKNOWN rate",
          "held fixed while the directional correct-guess rate is varied). This",
          "is an extension implemented by cgrc.bayes, not the original Szigeti",
          "estimand.")
  else "Binary four-stratum CGRC (Normal-Inverse-Gamma conjugate posterior)."
  add("- Method: %s", meth)
  add("")
  add("## Input audit")
  add("")
  add("| Quantity | n |")
  add("|---|---|")
  add("| Rows uploaded | %d |", s[["n_input"]])
  add("| Analysed | %d |", nrow(f$trial))
  add("| Missing condition | %d |", s[["missing_condition"]])
  add("| Missing guess | %d |", s[["missing_guess"]])
  add("| Missing outcome | %d |", s[["missing_outcome"]])
  add("| Non-numeric outcome | %d |", s[["nonnumeric_outcome"]])
  add("| Observed UNKNOWN responses | %d |", s[["observed_unknown"]])
  if (isTRUE(f$n_excl_unknown > 0))
    add("| UNKNOWN excluded (complete-case) | %d |", f$n_excl_unknown)
  add("")

  if (f$mode == "unknown") {
    st <- cgr_unknown_strata(f$trial); n <- lengths(st)
    add("## Stratum counts (UNKNOWN preserved)")
    add("")
    add("| Stratum | n |")
    add("|---|---|")
    for (k in UNKNOWN_STRATA) add("| %s | %d |", k, n[[k]])
    add("")
    add("- Observed directional CGR: %.4f", f$ufit$observed_directional_cgr)
    add("- Observed UNKNOWN rate: %.4f (held fixed at %.4f)",
        f$ufit$observed_unknown_rate, f$ufit$target_unknown_rate)
    add("- n total / directional / UNKNOWN: %d / %d / %d",
        f$ufit$n_total, f$ufit$n_directional, f$ufit$n_unknown)
    sm <- f$ufit$summary; z <- cgr_unknown_reference_line_test(f$trial)
    h <- f$uhead
    obs_est <- sm$post_mean[1]; adj_est <- sm$post_mean[2]
  } else {
    st <- cgr_strata(f$trial)
    add("## Stratum counts")
    add("")
    add("| Stratum | n |")
    add("|---|---|")
    for (k in STRATA) add("| %s | %d |", k, length(st[[k]]))
    add("")
    add("- Observed CGR: %.4f", f$fit$observed_cgr)
    sm <- f$fit$summary; z <- cgr_reference_line_test(f$trial, f$fit$observed_cgr)
    h <- f$head
    obs_est <- sm$post_mean[1]; adj_est <- sm$post_mean[2]
  }
  add("")
  add("## Estimates")
  add("")
  add("| | posterior mean | 95%% CrI | P(favourable) |")
  add("|---|---|---|---|")
  add("| Raw (observed CGR) | %.3f | %.3f to %.3f | %.3f |",
      sm$post_mean[1], sm$cri_lo[1], sm$cri_hi[1], sm$p_favourable[1])
  add("| Adjusted (CGR 0.50) | %.3f | %.3f to %.3f | %.3f |",
      sm$post_mean[2], sm$cri_lo[2], sm$cri_hi[2], sm$p_favourable[2])
  add("")
  add("- Meaningful-difference threshold delta: %.3f outcome units", f$delta)
  add("- P(meaningful) raw / adjusted: %.3f / %.3f",
      h$p_meaningful_obs, h$p_meaningful_blind)
  add("")
  add("## Identity check")
  add("")
  add("At the observed CGR the reweighting is a no-op: Delta = raw arm-mean")
  add("difference to %.1e (should be ~0).", abs(z$D_at_obs - z$raw_mean_diff))
  add("")
  add("## Region of practical equivalence (at CGR 0.50)")
  add("")
  rope <- if (f$mode == "unknown") f$urope else f$rope
  i <- which.min(abs(rope$cgr - 0.5))
  add("- P(meaningful benefit): %.3f", rope$p_benefit[i])
  add("- P(practically negligible): %.3f", rope$p_negligible[i])
  add("- P(meaningful harm): %.3f", rope$p_harm[i])
  add("")
  add("_Report text: %s_", h$text)
  L
}

# Should pct_attenuation be shown? No when the unadjusted estimate is not
# distinguishable from zero (its CrI includes 0) or when adjusted and unadjusted
# have opposite signs (the ratio is then > 100% and meaningless, e.g. "146.9%").
cgrc_pct_ok <- function(unadj_est, unadj_lo, unadj_hi, adj_est) {
  distinct  <- !(unadj_lo <= 0 && unadj_hi >= 0)
  same_sign <- sign(unadj_est) == sign(adj_est)
  distinct && same_sign
}

# Plain-language readout for a design, computed from the lookup (never
# hand-written). States the numbers and the trade-off; it does NOT pronounce a
# design "safe" or "acceptable" - that is the user's judgment, not the tool's.
# The two criteria are named explicitly: the unadjusted rate is frequentist
# p<0.05; the adjusted rate is Bayesian posterior P(favourable) > 0.95 -
# comparable in spirit, not the same quantity.
cgrc_verdict <- function(lut, n, p_cg, true_effect, mu_aeb = 7.7) {
  minstr <- cgr_min_stratum(n, p_cg)
  fp  <- cgrc_op_at(lut, n, p_cg, true_effect, 0, 1, mu_aeb)   # pure expectancy
  feas <- if (minstr < 15) sprintf(
    paste0(" (The smallest stratum averages ~%.0f participants here, so the ",
           "estimand can be undefined for some trials - see the feasibility ",
           "readout.)"), minstr) else ""
  if (true_effect == 0) {
    sprintf(paste0("At n=%d with %.0f%% correct guessing and no true effect: ",
      "when the apparent signal is pure expectancy, an unadjusted analysis ",
      "reaches p<0.05 in %.0f%% of simulated trials, while the CGR-adjusted ",
      "analysis reaches posterior P>0.95 in %.0f%%.%s"),
      n, 100 * p_cg, 100 * fp$freq_sig, 100 * fp$p_fav_gt_95, feas)
  } else {
    pw <- cgrc_op_at(lut, n, p_cg, true_effect, 1, 0, mu_aeb)  # clean power
    sprintf(paste0("At n=%d with %.0f%% correct guessing: for a real %.1f-point ",
      "effect the CGR-adjusted analysis reaches posterior P>0.95 in %.0f%% of ",
      "simulated trials. When the apparent effect is instead pure expectancy, ",
      "an unadjusted analysis reaches p<0.05 in %.0f%% of trials and the ",
      "adjusted analysis in %.0f%%. Weigh that trade-off against your own ",
      "priorities.%s"),
      n, 100 * p_cg, true_effect, 100 * pw$p_fav_gt_95,
      100 * fp$freq_sig, 100 * fp$p_fav_gt_95, feas)
  }
}
