# Support functions for the Shiny design app (inst/app/app.R). These are UI,
# interpolation and input-normalisation helpers ONLY. Every statistical quantity
# still comes from the package's cgr_* functions - the app never carries its own
# copy of the estimand.

# Accessor for the precomputed operating-characteristics lookup table shipped in
# inst/extdata (generated by data-raw/build_lookup.R). One row per
# (n, p_cg, true_effect) x (DTE, AEB) scenario. cgr_operating(n_trials = 500)
# takes ~9 s, so the app reads this instead of calling it on a slider.
cgrc_lookup <- function() {
  f <- system.file("extdata", "cgrc_lookup.rds", package = "cgrc.bayes")
  if (!nzchar(f) || !file.exists(f)) {
    stop("lookup table not found; run data-raw/build_lookup.R then reinstall.",
         call. = FALSE)
  }
  readRDS(f)
}

# Launch the Shiny design app ("Is CGR adjustment safe for my trial?").
cgrc_app <- function(...) {
  if (!requireNamespace("shiny", quietly = TRUE)) {
    stop("the app needs the 'shiny' package: install.packages('shiny')",
         call. = FALSE)
  }
  app_dir <- system.file("app", package = "cgrc.bayes")
  if (!nzchar(app_dir)) stop("app directory not found in the install", call. = FALSE)
  shiny::runApp(app_dir, ...)
}

# Bilinear interpolation of a single column over two grid axes.
.cgrc_bilin <- function(df, xcol, ycol, vcol, x, y) {
  xs <- sort(unique(df[[xcol]])); ys <- sort(unique(df[[ycol]]))
  x <- min(max(x, min(xs)), max(xs)); y <- min(max(y, min(ys)), max(ys))
  x0 <- max(xs[xs <= x]); x1 <- min(xs[xs >= x])
  y0 <- max(ys[ys <= y]); y1 <- min(ys[ys >= y])
  g  <- function(xx, yy) df[[vcol]][df[[xcol]] == xx & df[[ycol]] == yy][1]
  tx <- if (x1 == x0) 0 else (x - x0) / (x1 - x0)
  ty <- if (y1 == y0) 0 else (y - y0) / (y1 - y0)
  (1 - tx) * (1 - ty) * g(x0, y0) + tx * (1 - ty) * g(x1, y0) +
    (1 - tx) * ty * g(x0, y1) + tx * ty * g(x1, y1)
}

# Operating characteristics for one (DTE, AEB) scenario at arbitrary (n, p_cg),
# a grid true_effect and a grid mu_aeb (expectancy magnitude), read from the
# lookup. Bilinear in (n, p_cg); true_effect and mu_aeb are snapped to their
# nearest grid values. `mu_aeb` only matters for AEB-on rows (with AEB off there
# is no expectancy term). Returns a one-row data.frame of interpolated metrics
# plus an `interpolated` flag. Works whether or not the lookup has a mu_aeb
# column (older 7.7-only tables are treated as a single level).
cgrc_op_at <- function(lut, n, p_cg, true_effect, dte, aeb, mu_aeb = 7.7) {
  sub <- lut[lut$DTE == dte & lut$AEB == aeb, ]
  ma  <- NA_real_
  if ("mu_aeb" %in% names(sub)) {
    mas <- sort(unique(sub$mu_aeb)); ma <- mas[which.min(abs(mas - mu_aeb))]
    sub <- sub[sub$mu_aeb == ma, ]
  }
  effs <- sort(unique(sub$true_effect))
  eff  <- effs[which.min(abs(effs - true_effect))]
  sub  <- sub[sub$true_effect == eff, ]
  if (!nrow(sub)) stop("no lookup rows for that scenario", call. = FALSE)
  # a matched-to-two-sided-p<0.05 comparator is available in newer lookups
  metrics <- c("unadj_bias", "adj_bias", "adj_rmse", "coverage95",
               "p_fav_gt_95", "freq_sig", "empty_stratum_rate")
  if ("p_fav_gt_975" %in% names(sub)) metrics <- c(metrics, "p_fav_gt_975")
  vals <- vapply(metrics, function(m) .cgrc_bilin(sub, "n", "p_cg", m, n, p_cg),
                 numeric(1))
  on_grid <- n %in% sub$n && p_cg %in% sub$p_cg
  # clamped: the requested n or p_cg is OUTSIDE this level's grid, so an edge
  # value is being reported under the requested label (e.g. n=60 is not
  # simulated at mu_aeb != 7.7, so it reads the n=80 row). Flag it, do not hide.
  clamped <- n < min(sub$n) || n > max(sub$n) ||
             p_cg < min(sub$p_cg) || p_cg > max(sub$p_cg)
  cbind(data.frame(n = n, p_cg = p_cg, true_effect = eff, mu_aeb = ma,
                   DTE = dte, AEB = aeb,
                   interpolated = !on_grid, clamped = clamped),
        as.data.frame(as.list(vals)))
}

# Power of the ADJUSTED analysis to detect true_effect, over n, at fixed p_cg.
# This is the DTE-on / AEB-off row - the honest, expectancy-free power (the
# AEB-on rows mix drug and expectancy, so their p_fav is not clean power).
# With AEB off the expectancy magnitude is irrelevant, so mu_aeb does not enter.
cgrc_power_curve <- function(lut, p_cg, true_effect) {
  ns <- sort(unique(lut$n))
  data.frame(n = ns,
             power = vapply(ns, function(nn)
               cgrc_op_at(lut, nn, p_cg, true_effect, 1, 0)$p_fav_gt_95,
               numeric(1)))
}

# Normalise an arm / guess coding to "AC"/"PL", erroring (naming the offending
# level) rather than guessing. Accepts AC/PL, MD/PL, active/placebo,
# drug/placebo, microdose/placebo, 1/0, TRUE/FALSE, yes/no.
cgrc_normalise_arm <- function(x, what = "value") {
  s <- toupper(trimws(as.character(x)))
  active  <- c("AC", "MD", "ACTIVE", "DRUG", "MICRODOSE", "TREATMENT",
               "TRUE", "T", "1", "YES", "Y")
  placebo <- c("PL", "PLACEBO", "CONTROL", "SHAM", "FALSE", "F", "0", "NO", "N")
  out <- ifelse(s %in% active, "AC", ifelse(s %in% placebo, "PL", NA_character_))
  bad <- unique(as.character(x)[is.na(out)])
  if (length(bad)) {
    stop(sprintf(paste0("could not map %s level(s) %s to active/placebo; ",
                        "recode to AC/PL (active/placebo)."),
                 what, paste(shQuote(bad), collapse = ", ")), call. = FALSE)
  }
  out
}

# Normalise a GUESS coding to "AC"/"PL"/"UNKNOWN". Unlike cgrc_normalise_arm(),
# this optionally recognises an explicit UNKNOWN / "I do not know" response and
# keeps missing data (NA or blank) as missing - an observed UNKNOWN response and
# absent data are different things and must not be conflated. Unrecognised values
# error, naming the offending labels, rather than being guessed. When
# allow_unknown = FALSE an UNKNOWN synonym is treated as unrecognised (rejected
# explicitly), so the caller cannot silently admit UNKNOWN into a binary analysis.
cgrc_normalise_guess <- function(x, allow_unknown = FALSE, unknown_labels = NULL,
                                 what = "treatment guessed") {
  raw <- as.character(x)
  s <- toupper(trimws(raw))
  # normalise apostrophe variants to a plain ' with fixed byte replacement so this
  # works in a C locale too, where a multibyte regex character class fails. \u
  # escapes keep the source pure-ASCII; useBytes avoids any locale translation.
  for (ap in c("\u2019", "\u02bc", "\u2018", "`"))
    s <- gsub(ap, "'", s, fixed = TRUE, useBytes = TRUE)
  s <- gsub("[[:space:]]+", " ", s)             # collapse internal whitespace
  active  <- c("AC", "MD", "ACTIVE", "DRUG", "MICRODOSE", "TREATMENT",
               "TRUE", "T", "1", "YES", "Y")
  placebo <- c("PL", "PLACEBO", "CONTROL", "SHAM", "FALSE", "F", "0", "NO", "N")
  unknown <- c("UNKNOWN", "UNSURE", "UNCERTAIN", "NOT SURE", "DO NOT KNOW",
               "DON'T KNOW", "DID NOT KNOW", "I DO NOT KNOW", "I DON'T KNOW",
               "DK", "IDK",
               toupper(trimws(as.character(unknown_labels))))
  missing <- is.na(raw) | s == ""               # NA / blank stay missing, never UNKNOWN
  out <- rep(NA_character_, length(s))
  out[s %in% active]  <- "AC"
  out[s %in% placebo] <- "PL"
  if (allow_unknown) out[s %in% unknown] <- "UNKNOWN"
  out[missing] <- NA_character_
  bad <- unique(raw[!missing & is.na(out)])      # present, but mapped to nothing
  if (length(bad)) {
    hint <- if (allow_unknown) "AC/PL or an UNKNOWN response" else "AC/PL (active/placebo)"
    stop(sprintf("could not map %s level(s) %s to %s; recode them.",
                 what, paste(shQuote(bad), collapse = ", "), hint), call. = FALSE)
  }
  out
}

# Should pct_attenuation be shown? No when the unadjusted estimate is not
# distinguishable from zero (its CrI includes 0) or when adjusted and unadjusted
# have opposite signs (the ratio is then > 100% and meaningless, e.g. "146.9%").
cgrc_pct_ok <- function(unadj_est, unadj_lo, unadj_hi, adj_est) {
  distinct  <- !(unadj_lo <= 0 && unadj_hi >= 0)
  same_sign <- sign(unadj_est) == sign(adj_est)
  distinct && same_sign
}

# Plain-language readout for a design, computed from the lookup (never
# hand-written). States the numbers and the trade-off; it does NOT pronounce a
# design "safe" or "acceptable" - that is the user's judgment, not the tool's.
# The two criteria are named explicitly: the unadjusted rate is frequentist
# p<0.05; the adjusted rate is Bayesian posterior P(favourable) > 0.95 -
# comparable in spirit, not the same quantity.
cgrc_verdict <- function(lut, n, p_cg, true_effect, mu_aeb = 7.7) {
  minstr <- cgr_min_stratum(n, p_cg)
  fp  <- cgrc_op_at(lut, n, p_cg, true_effect, 0, 1, mu_aeb)   # pure expectancy
  feas <- if (minstr < 15) sprintf(
    paste0(" (The smallest stratum averages ~%.0f participants here, so the ",
           "estimand can be undefined for some trials - see the feasibility ",
           "readout.)"), minstr) else ""
  if (true_effect == 0) {
    sprintf(paste0("At n=%d with %.0f%% correct guessing and no true effect: ",
      "when the apparent signal is pure expectancy, an unadjusted analysis ",
      "reaches p<0.05 in %.0f%% of simulated trials, while the CGR-adjusted ",
      "analysis reaches posterior P>0.95 in %.0f%%.%s"),
      n, 100 * p_cg, 100 * fp$freq_sig, 100 * fp$p_fav_gt_95, feas)
  } else {
    pw <- cgrc_op_at(lut, n, p_cg, true_effect, 1, 0, mu_aeb)  # clean power
    sprintf(paste0("At n=%d with %.0f%% correct guessing: for a real %.1f-point ",
      "effect the CGR-adjusted analysis reaches posterior P>0.95 in %.0f%% of ",
      "simulated trials. When the apparent effect is instead pure expectancy, ",
      "an unadjusted analysis reaches p<0.05 in %.0f%% of trials and the ",
      "adjusted analysis in %.0f%%. Weigh that trade-off against your own ",
      "priorities.%s"),
      n, 100 * p_cg, true_effect, 100 * pw$p_fav_gt_95,
      100 * fp$freq_sig, 100 * fp$p_fav_gt_95, feas)
  }
}
