# Support functions for the Shiny design app (inst/app/app.R). These are UI,
# interpolation and input-normalisation helpers ONLY. Every statistical quantity
# still comes from the package's cgr_* functions - the app never carries its own
# copy of the estimand.

# Accessor for the precomputed operating-characteristics lookup table shipped in
# inst/extdata (generated by data-raw/build_lookup.R). One row per
# (n, p_cg, true_effect) x (DTE, AEB) scenario. cgr_operating(n_trials = 500)
# takes ~9 s, so the app reads this instead of calling it on a slider.
cgrc_lookup <- function() {
  f <- system.file("extdata", "cgrc_lookup.rds", package = "cgrc.bayes")
  if (!nzchar(f) || !file.exists(f)) {
    stop("lookup table not found; run data-raw/build_lookup.R then reinstall.",
         call. = FALSE)
  }
  readRDS(f)
}

# Launch the Shiny design app ("Is CGR adjustment safe for my trial?").
cgrc_app <- function(...) {
  if (!requireNamespace("shiny", quietly = TRUE)) {
    stop("the app needs the 'shiny' package: install.packages('shiny')",
         call. = FALSE)
  }
  app_dir <- system.file("app", package = "cgrc.bayes")
  if (!nzchar(app_dir)) stop("app directory not found in the install", call. = FALSE)
  shiny::runApp(app_dir, ...)
}

# Bilinear interpolation of a single column over two grid axes.
.cgrc_bilin <- function(df, xcol, ycol, vcol, x, y) {
  xs <- sort(unique(df[[xcol]])); ys <- sort(unique(df[[ycol]]))
  x <- min(max(x, min(xs)), max(xs)); y <- min(max(y, min(ys)), max(ys))
  x0 <- max(xs[xs <= x]); x1 <- min(xs[xs >= x])
  y0 <- max(ys[ys <= y]); y1 <- min(ys[ys >= y])
  g  <- function(xx, yy) df[[vcol]][df[[xcol]] == xx & df[[ycol]] == yy][1]
  tx <- if (x1 == x0) 0 else (x - x0) / (x1 - x0)
  ty <- if (y1 == y0) 0 else (y - y0) / (y1 - y0)
  (1 - tx) * (1 - ty) * g(x0, y0) + tx * (1 - ty) * g(x1, y0) +
    (1 - tx) * ty * g(x0, y1) + tx * ty * g(x1, y1)
}

# Operating characteristics for one (DTE, AEB) scenario at arbitrary (n, p_cg)
# and a grid true_effect, read from the lookup. Bilinear in (n, p_cg);
# true_effect is snapped to the nearest grid value. Returns a one-row data.frame
# of interpolated metrics plus an `interpolated` flag.
cgrc_op_at <- function(lut, n, p_cg, true_effect, dte, aeb) {
  effs <- sort(unique(lut$true_effect))
  eff  <- effs[which.min(abs(effs - true_effect))]
  sub  <- lut[lut$true_effect == eff & lut$DTE == dte & lut$AEB == aeb, ]
  if (!nrow(sub)) stop("no lookup rows for that scenario", call. = FALSE)
  metrics <- c("unadj_bias", "adj_bias", "adj_rmse", "coverage95",
               "p_fav_gt_95", "freq_sig", "empty_stratum_rate")
  vals <- vapply(metrics, function(m) .cgrc_bilin(sub, "n", "p_cg", m, n, p_cg),
                 numeric(1))
  on_grid <- n %in% sub$n && p_cg %in% sub$p_cg
  cbind(data.frame(n = n, p_cg = p_cg, true_effect = eff, DTE = dte, AEB = aeb,
                   interpolated = !on_grid),
        as.data.frame(as.list(vals)))
}

# Power of the ADJUSTED analysis to detect true_effect, over n, at fixed p_cg.
# This is the DTE-on / AEB-off row - the honest, expectancy-free power (the
# AEB-on rows mix drug and expectancy, so their p_fav is not clean power).
cgrc_power_curve <- function(lut, p_cg, true_effect) {
  ns <- sort(unique(lut$n))
  data.frame(n = ns,
             power = vapply(ns, function(nn)
               cgrc_op_at(lut, nn, p_cg, true_effect, 1, 0)$p_fav_gt_95,
               numeric(1)))
}

# Normalise an arm / guess coding to "AC"/"PL", erroring (naming the offending
# level) rather than guessing. Accepts AC/PL, MD/PL, active/placebo,
# drug/placebo, microdose/placebo, 1/0, TRUE/FALSE, yes/no.
cgrc_normalise_arm <- function(x, what = "value") {
  s <- toupper(trimws(as.character(x)))
  active  <- c("AC", "MD", "ACTIVE", "DRUG", "MICRODOSE", "TREATMENT",
               "TRUE", "T", "1", "YES", "Y")
  placebo <- c("PL", "PLACEBO", "CONTROL", "SHAM", "FALSE", "F", "0", "NO", "N")
  out <- ifelse(s %in% active, "AC", ifelse(s %in% placebo, "PL", NA_character_))
  bad <- unique(as.character(x)[is.na(out)])
  if (length(bad)) {
    stop(sprintf(paste0("could not map %s level(s) %s to active/placebo; ",
                        "recode to AC/PL (active/placebo)."),
                 what, paste(shQuote(bad), collapse = ", ")), call. = FALSE)
  }
  out
}

# Should pct_attenuation be shown? No when the unadjusted estimate is not
# distinguishable from zero (its CrI includes 0) or when adjusted and unadjusted
# have opposite signs (the ratio is then > 100% and meaningless, e.g. "146.9%").
cgrc_pct_ok <- function(unadj_est, unadj_lo, unadj_hi, adj_est) {
  distinct  <- !(unadj_lo <= 0 && unadj_hi >= 0)
  same_sign <- sign(unadj_est) == sign(adj_est)
  distinct && same_sign
}

# Plain-language verdict for a design, computed from the lookup (never
# hand-written). Combines adjusted power (DTE on / AEB off) with the unadjusted
# false-positive rate under pure expectancy (DTE off / AEB on).
cgrc_verdict <- function(lut, n, p_cg, true_effect) {
  minstr <- cgr_min_stratum(n, p_cg)
  fp  <- cgrc_op_at(lut, n, p_cg, true_effect, 0, 1)   # pure expectancy
  feas <- if (minstr < 15) sprintf(
    paste0(" Caution: the smallest stratum averages ~%.0f participants at this ",
           "design, so CGR adjustment may be unstable or undefined here."),
    minstr) else ""
  if (true_effect == 0) {
    sprintf(paste0("At n=%d with %.0f%% correct guessing and no true effect, ",
      "an unadjusted analysis would report a false positive %.0f%% of the time ",
      "when the apparent signal is pure expectancy; the CGR-adjusted analysis ",
      "flags it only %.0f%% of the time.%s"),
      n, 100 * p_cg, 100 * fp$freq_sig, 100 * fp$p_fav_gt_95, feas)
  } else {
    pw <- cgrc_op_at(lut, n, p_cg, true_effect, 1, 0)  # clean adjusted power
    sprintf(paste0("At n=%d with %.0f%% correct guessing, the adjusted analysis ",
      "has %.0f%% power to detect a %.1f-point effect. When the apparent effect ",
      "is pure expectancy, an unadjusted analysis would call it significant ",
      "%.0f%% of the time; the CGR-adjusted analysis flags it only %.0f%% of ",
      "the time.%s"),
      n, 100 * p_cg, 100 * pw$p_fav_gt_95, true_effect,
      100 * fp$freq_sig, 100 * fp$p_fav_gt_95, feas)
  }
}
